services:
  db:
    image: postgres:latest
    container_name: prototype_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: prototype
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: prototype_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data: