services:
  postgres:
    image: postgres:latest
    container_name: kaisertify-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kaiser
      POSTGRES_PASSWORD: kaiser
      POSTGRES_DB: kaisertify
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: